name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Build
        run: make build
      - name: Test
        run: make test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Windows binary
        run: make build

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: panda-windows
          path: panda.exe
